'use client'
import { Geist, Geist_Mono,Bebas_Neue  } from "next/font/google";
import "./globals.css";
import { MylistProvider } from "./context/MylistContext";

const bebas = Bebas_Neue({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-bebas'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebas.variable} antialiased`}
      >
        <main className="w-full h-full">
          <MylistProvider>
            {children}
          </MylistProvider>
        </main>
      </body>
    </html>
  );
}
