import { Geist, Geist_Mono,Bebas_Neue  } from "next/font/google";
import "./globals.css";
import { MagnifyingGlassIcon } from '@heroicons/react/24/outline'


const bebas = Bebas_Neue({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-bebas'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebas.variable} antialiased`}
      >
        <div className="flex flex-row items-center justify-between">
          <div className="flex flex-row items-center justify-evenly w-2/5"> 
            <h2 className="font-bebas font-bold text-red-700 text-5xl">Netflix</h2>
            <button className="font-medium">Home</button>
            <button className="font-medium">TV Show</button>
            <button className="font-medium">Movies</button>
            <button className="font-medium">New & Popular</button>
            <button className="font-medium">Browse by languages</button>
          </div>
          <div className="w-1/5 flex flex-row items-center justify-end">
            <MagnifyingGlassIcon className="h-5 w-5 mr-1" />
            <input
              className="bg-gray-800 h-5 w-30 mr-8 rounded-sm text-xs pl-2"
              placeholder="search..."
            />
            <div className="bg-white text-red-700 h-10 w-10 flex items-center justify-center rounded-full font-bold  mr-2">N</div>
            <span className="font-medium  mr-8">NextZy</span>
          </div>
        </div>
        
        {children}
      </body>
    </html>
  );
}
